#!/bin/sh

set -eu

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo test --tests
then
    echo "There are some test issues."
    exit 1
fi

exit 0